import type { Chair, HierarquiaEntry, Person, PageKey } from "./types";

// Sobe este número sempre que CHAIRS/PEOPLE/HIERARQUIA (os dados padrão de
// código) mudarem. A persistência no navegador (lib/persistence.ts) usa isso
// para descartar uma base salva antiga e incompatível em vez de "prender" o
// navegador numa versão anterior do painel para sempre.
export const BASE_DATA_VERSION = 3;

export const CHAIRS: Chair[] = [
  { id: "c001", nome: "Rafael Kerche de Oliveira", cargo: "CEO", nivel: "C-Level", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 10.2, prefixLocalidade: false },
  { id: "c002", nome: "Joao Angelo de Moraes", cargo: "Diretor Administrativo", nivel: "Diretoria", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 2.6, prefixLocalidade: false },
  { id: "c003", nome: "Domingos Savio Oriente Franciulli", cargo: "Diretor de Negócios", nivel: "Diretoria", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 0.1, prefixLocalidade: false },
  { id: "c004", nome: "Cleber Eduardo Vitorino", cargo: "Gerente Executivo de Riscos e Conformidade", nivel: "Gerência Executiva", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 2.0, prefixLocalidade: false },
  { id: "c005", nome: "Silvanira Squiapatti da Silva Lanconi", cargo: "Gerente Executivo Administrativo", nivel: "Gerência Executiva", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 3.2, prefixLocalidade: false },
  { id: "c006", nome: "Amaya Fernanda Dal Coleto de Albuquerque", cargo: "Gerente Executivo Financeiro", nivel: "Gerência Executiva", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 16.3, prefixLocalidade: false },
  { id: "c007", nome: "", cargo: "Gerente Executivo de Negócios", nivel: "Gerência Executiva", diretoria: "Negócios", cidade: "Capivari", tempoCasa: null, prefixLocalidade: false, vago: true },
  { id: "c008", nome: "Nelson Alves Quagliato", cargo: "Gerente Executivo Comercial Regional 2", nivel: "Gerência Executiva", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 10.4, prefixLocalidade: false },
  { id: "c009", nome: "Rafael Cavallante de Oliveira", cargo: "Gerente Executivo Comercial Regional 1", nivel: "Gerência Executiva", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 13.9, prefixLocalidade: false },
  { id: "c010", nome: "Matheus Ferreira", cargo: "Gerente de T.i.", nivel: "Gerência", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 7.5, prefixLocalidade: false },
  { id: "c011", nome: "Cristiano Aparecido Cremonese", cargo: "Gerente de Contabilidade", nivel: "Gerência", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 9.8, prefixLocalidade: false },
  { id: "c012", nome: "Luis Guilherme Apolinario", cargo: "Gerente Financeiro", nivel: "Gerência", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 10.7, prefixLocalidade: false },
  { id: "c013", nome: "Luiz Tiago Correa Moretti", cargo: "Gerente de Operações", nivel: "Gerência", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 4.1, prefixLocalidade: false },
  { id: "c014", nome: "Milene Barratella", cargo: "Gerente de Operações", nivel: "Gerência", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 10.1, prefixLocalidade: false },
  { id: "c015", nome: "Paulo Augusto Barreto Junior", cargo: "Gerente de Operações", nivel: "Gerência", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 1.0, prefixLocalidade: false },
  { id: "c016", nome: "Alessandro Sergio Agatelli", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Itupeva", tempoCasa: 7.5, prefixLocalidade: true },
  { id: "c017", nome: "Anaisa Moroni Haddad", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Rafard", tempoCasa: 8.3, prefixLocalidade: true },
  { id: "c018", nome: "Andre Ricardo Trentin", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Salto", tempoCasa: 3.2, prefixLocalidade: true },
  { id: "c019", nome: "Bruna Hiromi Ushiwa Pimenta", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Porto Feliz", tempoCasa: 15.9, prefixLocalidade: true },
  { id: "c020", nome: "Daniel Aparecido Travaioli", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Monte Mor", tempoCasa: 6.5, prefixLocalidade: true },
  { id: "c021", nome: "Hipolito Amancio Bizarria Junior", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Cesário Lange", tempoCasa: 13.2, prefixLocalidade: true },
  { id: "c022", nome: "Igor Bolzan Basso", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Jumirim", tempoCasa: 6.3, prefixLocalidade: true },
  { id: "c023", nome: "Jose Henrique Diorio Junior", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Tietê", tempoCasa: 2.7, prefixLocalidade: true },
  { id: "c024", nome: "Jose Luiz Pereira Guilherme Junior", cargo: "Gerente de Performance Corporativa", nivel: "Gerência", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 10.6, prefixLocalidade: false },
  { id: "c025", nome: "Jose Paulo Picarelli Avancini", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Vinhedo", tempoCasa: 3.4, prefixLocalidade: true },
  { id: "c026", nome: "Juliano Zacarias", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Boituva", tempoCasa: 5.7, prefixLocalidade: true },
  { id: "c027", nome: "Julio Augusto de Camargo Toledo", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Pereiras", tempoCasa: 10.4, prefixLocalidade: true },
  { id: "c028", nome: "Liliane Patricia Rodrigues Barbosa", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Cabreúva", tempoCasa: 8.6, prefixLocalidade: true },
  { id: "c029", nome: "Luciane Zanetti", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Cerquilho", tempoCasa: 16.8, prefixLocalidade: true },
  { id: "c030", nome: "Luiz Rafael Grella", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Louveira", tempoCasa: 9.0, prefixLocalidade: true },
  { id: "c031", nome: "Rogerio Toshio de Castro", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Indaiatuba", tempoCasa: 4.5, prefixLocalidade: true },
  { id: "c032", nome: "Shirlei Aparecida Rossi Ambrozin", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 7.4, prefixLocalidade: true },
  { id: "c033", nome: "Sidnei Roberto Betarelli", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Elias Fausto", tempoCasa: 5.6, prefixLocalidade: true },
  { id: "c034", nome: "Uilian Fernando Ribeiro", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Porangaba", tempoCasa: 2.4, prefixLocalidade: true },
  { id: "c098", nome: "Alan Marques", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Vinhedo", tempoCasa: 0.4, prefixLocalidade: true },
  { id: "c099", nome: "Alex Henrique Ambrosio", cargo: "Gerente de Relacionamento I", nivel: "Gerência", diretoria: "Negócios", cidade: "Boituva", tempoCasa: 8.8, prefixLocalidade: true },
  { id: "c100", nome: "Aline Capelari", cargo: "Gerente de Relacionamento I", nivel: "Gerência", diretoria: "Negócios", cidade: "Cerquilho", tempoCasa: 6.2, prefixLocalidade: true },
  { id: "c101", nome: "Aline Suzana Lucio", cargo: "Gerente de Relacionamento I", nivel: "Gerência", diretoria: "Negócios", cidade: "Elias Fausto", tempoCasa: 3.9, prefixLocalidade: true },
  { id: "c102", nome: "Ana Paula Leite Santos", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 7.4, prefixLocalidade: true },
  { id: "c103", nome: "Ana Paula Moreira", cargo: "Gerente de Relacionamento Digital", nivel: "Gerência", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 15.1, prefixLocalidade: false },
  { id: "c104", nome: "Anderson Kazunori Ikenoue", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Cabreúva", tempoCasa: 0.9, prefixLocalidade: true },
  { id: "c105", nome: "Arthur do Nascimento", cargo: "Gerente de Relacionamento I", nivel: "Gerência", diretoria: "Negócios", cidade: "Vinhedo", tempoCasa: 1.1, prefixLocalidade: true },
  { id: "c106", nome: "Camila Daniel", cargo: "Gerente de Relacionamento I", nivel: "Gerência", diretoria: "Negócios", cidade: "Monte Mor", tempoCasa: 0.9, prefixLocalidade: true },
  { id: "c107", nome: "Carolina Aparecida Almeida da Silva Mendonca", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Indaiatuba", tempoCasa: 2.7, prefixLocalidade: true },
  { id: "c108", nome: "Celia Rodrigues Alves", cargo: "Gerente de Relacionamento I", nivel: "Gerência", diretoria: "Negócios", cidade: "Louveira", tempoCasa: 7.1, prefixLocalidade: true },
  { id: "c109", nome: "Claudio Roberto de Almeida", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Boituva", tempoCasa: 6.8, prefixLocalidade: true },
  { id: "c110", nome: "Daniela Beneton Caciatore", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Jumirim", tempoCasa: 2.8, prefixLocalidade: true },
  { id: "c111", nome: "Daniela de Oliveira Miranda", cargo: "Gerente de Relacionamento I", nivel: "Gerência", diretoria: "Negócios", cidade: "Porangaba", tempoCasa: 3.2, prefixLocalidade: true },
  { id: "c112", nome: "Dayna Criser Aparecida Felix Camilo Santos", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Porto Feliz", tempoCasa: 1.7, prefixLocalidade: true },
  { id: "c113", nome: "Denize Nunes Alves", cargo: "Gerente de Relacionamento I", nivel: "Gerência", diretoria: "Negócios", cidade: "Cabreúva", tempoCasa: 7.2, prefixLocalidade: true },
  { id: "c114", nome: "Douglas Peregrino", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Indaiatuba", tempoCasa: 0.5, prefixLocalidade: true },
  { id: "c115", nome: "Emily Daiane Dias Soares", cargo: "Gerente de Relacionamento I", nivel: "Gerência", diretoria: "Negócios", cidade: "Cesário Lange", tempoCasa: 2.5, prefixLocalidade: true },
  { id: "c116", nome: "Eric Donizeti dos Santos", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Elias Fausto", tempoCasa: 1.4, prefixLocalidade: true },
  { id: "c117", nome: "Fabiana Maria Assalin Dias Pacheco", cargo: "Gerente de Relacionamento I", nivel: "Gerência", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 6.6, prefixLocalidade: true },
  { id: "c118", nome: "Fabio Francis Carlos Nahum", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Porto Feliz", tempoCasa: 9.2, prefixLocalidade: true },
  { id: "c119", nome: "Fabio de Souza Correa Rezende da Costa", cargo: "Gerente de Relacionamento I", nivel: "Gerência", diretoria: "Negócios", cidade: "Mombuca", tempoCasa: 2.7, prefixLocalidade: true },
  { id: "c120", nome: "Felipe Augusto Camerin Santarem", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Tietê", tempoCasa: 5.1, prefixLocalidade: true },
  { id: "c121", nome: "Fernando Quibao Neto", cargo: "Gerente de Relacionamento I", nivel: "Gerência", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 4.1, prefixLocalidade: true },
  { id: "c122", nome: "Gabrielle Barbosa de Oliveira Ivolella", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Monte Mor", tempoCasa: 8.5, prefixLocalidade: true },
  { id: "c123", nome: "Guilherme Tascare", cargo: "Gerente de Relacionamento I", nivel: "Gerência", diretoria: "Negócios", cidade: "Pereiras", tempoCasa: 3.2, prefixLocalidade: true },
  { id: "c124", nome: "Gustavo Casarini Del Debbio", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Cerquilho", tempoCasa: 5.2, prefixLocalidade: true },
  { id: "c125", nome: "Julia Almeida Villa Veronezi", cargo: "Gerente de Relacionamento I", nivel: "Gerência", diretoria: "Negócios", cidade: "Porto Feliz", tempoCasa: 8.1, prefixLocalidade: true },
  { id: "c126", nome: "Julia Wurgler Zorzi", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Itupeva", tempoCasa: 0.7, prefixLocalidade: true },
  { id: "c127", nome: "Keli Fernanda da Silva Rodrigues Miranda", cargo: "Gerente de Relacionamento I", nivel: "Gerência", diretoria: "Negócios", cidade: "Cesário Lange", tempoCasa: 13.8, prefixLocalidade: true },
  { id: "c128", nome: "Larissa Fernandes", cargo: "Gerente de Relacionamento I", nivel: "Gerência", diretoria: "Negócios", cidade: "Pereiras", tempoCasa: 2.8, prefixLocalidade: true },
  { id: "c129", nome: "Leila de Andrade da Cruz Liberato", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Vinhedo", tempoCasa: 1.6, prefixLocalidade: true },
  { id: "c130", nome: "Lucas Felicio dos Santos", cargo: "Gerente de Relacionamento I", nivel: "Gerência", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 10.6, prefixLocalidade: true },
  { id: "c131", nome: "Luciano Matheus Pinardi", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Itupeva", tempoCasa: 4.4, prefixLocalidade: true },
  { id: "c132", nome: "Luis Fernando Zaratin Marcon", cargo: "Gerente de Relacionamento I", nivel: "Gerência", diretoria: "Negócios", cidade: "Jumirim", tempoCasa: 7.4, prefixLocalidade: true },
  { id: "c133", nome: "Luiz Fernando de Almeida Patussi Lima", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Salto", tempoCasa: 3.8, prefixLocalidade: true },
  { id: "c134", nome: "Luiza Helena Pinto", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Salto", tempoCasa: 4.1, prefixLocalidade: true },
  { id: "c135", nome: "Marcio Pereira", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Valinhos", tempoCasa: 1.0, prefixLocalidade: true },
  { id: "c136", nome: "Mariana Forti Franzzini", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 8.0, prefixLocalidade: true },
  { id: "c137", nome: "Matheus Damasceno Ferreira", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Tietê", tempoCasa: 4.1, prefixLocalidade: true },
  { id: "c138", nome: "Miriane Regina de Almeida Gerevini", cargo: "Gerente de Relacionamento I", nivel: "Gerência", diretoria: "Negócios", cidade: "Tietê", tempoCasa: 7.7, prefixLocalidade: true },
  { id: "c139", nome: "Pedro Antonio Antunes Alves de Almeida", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Cesário Lange", tempoCasa: 3.1, prefixLocalidade: true },
  { id: "c140", nome: "Rafael Rodrigues de Barros Lobo", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 4.4, prefixLocalidade: true },
  { id: "c141", nome: "Rebeca Gabriel Leite Pereira", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Cerquilho", tempoCasa: 4.1, prefixLocalidade: true },
  { id: "c142", nome: "Reginaldo Oshima de Freitas", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Louveira", tempoCasa: 1.0, prefixLocalidade: true },
  { id: "c143", nome: "Rosaly Schiave Petrin", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Tietê", tempoCasa: 4.3, prefixLocalidade: true },
  { id: "c144", nome: "Sarah Peres Paiva Moreira", cargo: "Gerente de Relacionamento I", nivel: "Gerência", diretoria: "Negócios", cidade: "Rafard", tempoCasa: 2.5, prefixLocalidade: true },
  { id: "c145", nome: "Talita Cortes Radeschi Cavinatto", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Valinhos", tempoCasa: 1.2, prefixLocalidade: true },
  { id: "c146", nome: "Tatiane Piccin", cargo: "Gerente de Relacionamento I", nivel: "Gerência", diretoria: "Negócios", cidade: "Cerquilho", tempoCasa: 15.3, prefixLocalidade: true },
  { id: "c147", nome: "Thainara Lorenzon Cervelin", cargo: "Gerente de Relacionamento II", nivel: "Gerência", diretoria: "Negócios", cidade: "Louveira", tempoCasa: 1.4, prefixLocalidade: true },
  { id: "c148", nome: "Vagner Lopes", cargo: "Gerente de Relacionamento I", nivel: "Gerência", diretoria: "Negócios", cidade: "Porto Feliz", tempoCasa: 3.4, prefixLocalidade: true },
  { id: "c035", nome: "Leila Regina da Silva", cargo: "Coordenador de Agronegocios", nivel: "Coordenação", diretoria: "Negócios", cidade: "Capivari", tempoCasa: null, prefixLocalidade: false },
  { id: "c036", nome: "Renan Henrique Oliveira Muller", cargo: "Coordenador de Comunicação e Marketing", nivel: "Coordenação", diretoria: "Negócios", cidade: "Capivari", tempoCasa: null, prefixLocalidade: false },
  { id: "c037", nome: "Gabriella Fernanda Nichols", cargo: "Coordenador de Governança Corporativa", nivel: "Coordenação", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: null, prefixLocalidade: false },
  { id: "c038", nome: "Larisse de Paula", cargo: "Coordenador de Recuperação de Crédito", nivel: "Coordenação", diretoria: "Financeira", cidade: "Capivari", tempoCasa: null, prefixLocalidade: false },
  { id: "c039", nome: "Renato Alves da Silva", cargo: "Coordenador de Suprimentos", nivel: "Coordenação", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: null, prefixLocalidade: false },
  { id: "c040", nome: "Ailson Lima de Andrade", cargo: "Analista de Performance Corporativa Jr", nivel: "Analista", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 4.9, prefixLocalidade: false },
  { id: "c041", nome: "Aline Avanzi Costa", cargo: "Analista de Suprimentos Jr", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 2.1, prefixLocalidade: false },
  { id: "c042", nome: "Aline Brambilla da Silva", cargo: "Analista de Gestão de Pessoas Sr", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 7.9, prefixLocalidade: false },
  { id: "c043", nome: "Andressa Mader Bragion", cargo: "Analista Operacional Jr", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 7.2, prefixLocalidade: false },
  { id: "c044", nome: "Bianca Beltrame Mattar", cargo: "Analista de Crédito Pl", nivel: "Analista", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 7.0, prefixLocalidade: false },
  { id: "c045", nome: "Enzo Sachs", cargo: "Analista Operacional Jr", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 4.2, prefixLocalidade: false },
  { id: "c046", nome: "Gabriel Henrique Alves", cargo: "Analista de Tecnologia da Informação Sr", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 4.2, prefixLocalidade: false },
  { id: "c047", nome: "Jean Felipe Camillo", cargo: "Analista de Performance Corporativa Pl", nivel: "Analista", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 7.0, prefixLocalidade: false },
  { id: "c048", nome: "Jefferson Silva de Oliveira", cargo: "Analista Operacional Jr", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 10.1, prefixLocalidade: false },
  { id: "c049", nome: "Jessica Goncalves dos Santos", cargo: "Analista Financeiro Sr", nivel: "Analista", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 8.8, prefixLocalidade: false },
  { id: "c050", nome: "Juliana Grossi", cargo: "Analista de Gestão de Pessoas Sr", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 3.7, prefixLocalidade: false },
  { id: "c051", nome: "Kassio Rodrigo Fogaca", cargo: "Analista de Sistemas Pl", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 4.9, prefixLocalidade: false },
  { id: "c052", nome: "Katiely Fernanda Correa", cargo: "Analista Contábil Sr", nivel: "Analista", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 8.2, prefixLocalidade: false },
  { id: "c053", nome: "Larissa dos Santos Goncalves", cargo: "Analista de Riscos e Controles Jr", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 4.1, prefixLocalidade: false },
  { id: "c054", nome: "Ligia Delghingaro Pagotto", cargo: "Analista Financeiro Jr", nivel: "Analista", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 5.3, prefixLocalidade: false },
  { id: "c055", nome: "Luis Fernando Souza Andrade", cargo: "Analista Contábil Jr", nivel: "Analista", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 4.7, prefixLocalidade: false },
  { id: "c056", nome: "Manoela Tebom Santana", cargo: "Analista Operacional Jr", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 5.7, prefixLocalidade: false },
  { id: "c057", nome: "Mario Henrique Batistella", cargo: "Analista de Performance Corporativa Pl", nivel: "Analista", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 9.6, prefixLocalidade: false },
  { id: "c058", nome: "Matheus Henrique Souza de Moraes", cargo: "Analista de Agronegocios Jr", nivel: "Analista", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 3.8, prefixLocalidade: false },
  { id: "c059", nome: "Monica Roberta Armelin Moraes", cargo: "Analista de Gestão de Pessoas Sr", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 8.0, prefixLocalidade: false },
  { id: "c060", nome: "Rafael Amaral da Silva", cargo: "Analista Financeiro Pl", nivel: "Analista", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 3.1, prefixLocalidade: false },
  { id: "c061", nome: "Rafael Camilo da Silva", cargo: "Analista de Crédito Jr", nivel: "Analista", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 3.6, prefixLocalidade: false },
  { id: "c062", nome: "Renise Cristina Rolim de Moura", cargo: "Analista de Crédito Jr", nivel: "Analista", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 7.4, prefixLocalidade: false },
  { id: "c063", nome: "Roberto de Lucio", cargo: "Analista Financeiro Pl", nivel: "Analista", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 11.3, prefixLocalidade: false },
  { id: "c064", nome: "Rodolfo Santos Pereira Reges", cargo: "Analista de Administração de Pessoal Jr", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 3.8, prefixLocalidade: false },
  { id: "c065", nome: "Sabrina Rodrigues de Jesus", cargo: "Analista de Produtos e Serviços Pl", nivel: "Analista", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 5.9, prefixLocalidade: false },
  { id: "c066", nome: "Tiago Fernando Mutti", cargo: "Analista de Riscos e Controles Sr", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 3.2, prefixLocalidade: false },
  { id: "c067", nome: "Valentina Aparecida Rossi Antonelli", cargo: "Analista de Recuperação de Crédito Jr", nivel: "Analista", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 4.5, prefixLocalidade: false },
  { id: "c068", nome: "Vanessa Cristina Zumesteen", cargo: "Analista de Comunicação e Marketing Jr", nivel: "Analista", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 4.7, prefixLocalidade: false },
  { id: "c069", nome: "Yara Cerezer Pereira", cargo: "Analista de Produtos e Serviços Sr", nivel: "Analista", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 8.0, prefixLocalidade: false },
  { id: "c070", nome: "Yasmin Aparecida da Silva Castro", cargo: "Analista de Produtos e Serviços Jr", nivel: "Analista", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 3.7, prefixLocalidade: false },
  { id: "c071", nome: "Alexia Maria Cezar de Souza", cargo: "Coordenador Administrativo de P.A.", nivel: "Coordenação", diretoria: "Negócios", cidade: "Cabreúva", tempoCasa: 5.2, prefixLocalidade: true },
  { id: "c072", nome: "Amelia Cristina Angelieri Barbosa", cargo: "Coordenador Administrativo de P.A.", nivel: "Coordenação", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 31.8, prefixLocalidade: true },
  { id: "c073", nome: "Aristeu Serafim Junior", cargo: "Coordenador Administrativo de P.A.", nivel: "Coordenação", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 9.2, prefixLocalidade: true },
  { id: "c074", nome: "Bruna de Araujo Santos", cargo: "Coordenador Administrativo de P.A.", nivel: "Coordenação", diretoria: "Negócios", cidade: "Porto Feliz", tempoCasa: 5.4, prefixLocalidade: true },
  { id: "c075", nome: "Bruna Torres", cargo: "Coordenador Administrativo de P.A.", nivel: "Coordenação", diretoria: "Negócios", cidade: "Rafard", tempoCasa: 2.7, prefixLocalidade: true },
  { id: "c076", nome: "Bruno Werner Pasqualini", cargo: "Coordenador Administrativo de P.A.", nivel: "Coordenação", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 7.6, prefixLocalidade: true },
  { id: "c077", nome: "Camila Morais de Mello", cargo: "Coordenador Administrativo de P.A.", nivel: "Coordenação", diretoria: "Negócios", cidade: "Boituva", tempoCasa: 4.9, prefixLocalidade: true },
  { id: "c078", nome: "Danilo Borsato", cargo: "Coordenador Administrativo de P.A.", nivel: "Coordenação", diretoria: "Negócios", cidade: "Porto Feliz", tempoCasa: 2.7, prefixLocalidade: true },
  { id: "c079", nome: "Diego Domingues", cargo: "Coordenador Administrativo de P.A.", nivel: "Coordenação", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 5.3, prefixLocalidade: true },
  { id: "c080", nome: "Elaine Fumiko Sato Rodrigues", cargo: "Coordenador Administrativo de P.A.", nivel: "Coordenação", diretoria: "Negócios", cidade: "Indaiatuba", tempoCasa: 18.0, prefixLocalidade: true },
  { id: "c081", nome: "Gracia do Couto", cargo: "Coordenador Administrativo de P.A.", nivel: "Coordenação", diretoria: "Negócios", cidade: "Cerquilho", tempoCasa: 4.1, prefixLocalidade: true },
  { id: "c082", nome: "Leticia Fernanda Machado", cargo: "Coordenador Administrativo de P.A.", nivel: "Coordenação", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 5.7, prefixLocalidade: true },
  { id: "c083", nome: "Luana Cristina Camargo Estanislau", cargo: "Coordenador Administrativo de P.A.", nivel: "Coordenação", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 2.9, prefixLocalidade: true },
  { id: "c084", nome: "Marcos Paulo Rapete Canatelli", cargo: "Coordenador Administrativo de P.A.", nivel: "Coordenação", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 10.8, prefixLocalidade: true },
  { id: "c085", nome: "Nivaldo Armelin Junior", cargo: "Coordenador Administrativo de P.A.", nivel: "Coordenação", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 6.1, prefixLocalidade: true },
  { id: "c086", nome: "Rafael Moretti Queiroz", cargo: "Coordenador Administrativo de P.A.", nivel: "Coordenação", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 14.0, prefixLocalidade: true },
  { id: "c087", nome: "Renata Trevisan Leme Araujo", cargo: "Coordenador Administrativo de P.A.", nivel: "Coordenação", diretoria: "Negócios", cidade: "Louveira", tempoCasa: 8.1, prefixLocalidade: true },
  { id: "c088", nome: "Rodrigo Dias de Oliveira", cargo: "Coordenador Administrativo de P.A.", nivel: "Coordenação", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 11.4, prefixLocalidade: true },
  { id: "c089", nome: "Vanessa de Lourdes Ferrarezi", cargo: "Coordenador Administrativo de P.A.", nivel: "Coordenação", diretoria: "Negócios", cidade: "Porto Feliz", tempoCasa: 7.5, prefixLocalidade: true },
  { id: "c090", nome: "Anderson Vasconcelos Gava", cargo: "Especialista de Produtos e Serviços", nivel: "Especialista", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 16.0, prefixLocalidade: false },
  { id: "c091", nome: "Fernanda Aparecida Ravanelli Pagotto", cargo: "Especialista em Supervisão e Monitoramento", nivel: "Especialista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 10.8, prefixLocalidade: false },
  { id: "c092", nome: "Gabriel Henrique dos Santos Nogueira", cargo: "Especialista de Produtos e Serviços", nivel: "Especialista", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 7.4, prefixLocalidade: false },
  { id: "c093", nome: "Jose Roberto de Araujo", cargo: "Especialista em Supervisão e Monitoramento", nivel: "Especialista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 8.1, prefixLocalidade: false },
  { id: "c094", nome: "Leticia Batista Alexandre", cargo: "Especialista de Produtos e Serviços", nivel: "Especialista", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 5.4, prefixLocalidade: false },
  { id: "c095", nome: "Mayara Miori Degaspare", cargo: "Especialista Operacional de Agronegócios", nivel: "Especialista", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 2.6, prefixLocalidade: false },
  { id: "c096", nome: "Suelen Karen de Camargo Marcolino", cargo: "Especialista de Produtos e Serviços", nivel: "Especialista", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 7.5, prefixLocalidade: false },
  { id: "c097", nome: "Tais Regina Torres", cargo: "Especialista de Performance Corporativa", nivel: "Especialista", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 4.7, prefixLocalidade: false },
];

export const PEOPLE: Person[] = [
  { id: "P001", nome: "Rafael Kerche de Oliveira", nivel: "C-Level", cargo: "CEO", diretoria: "Financeira", chairId: "c001" },
  { id: "P002", nome: "Joao Angelo de Moraes", nivel: "Diretoria", cargo: "Diretor Administrativo", diretoria: "Administrativa", chairId: "c002" },
  { id: "P003", nome: "Domingos Savio Oriente Franciulli", nivel: "Diretoria", cargo: "Diretor de Negócios", diretoria: "Negócios", chairId: "c003" },
  { id: "P004", nome: "Cleber Eduardo Vitorino", nivel: "Gerência Executiva", cargo: "Gerente Executivo de Riscos e Conformidade", diretoria: "Administrativa", chairId: "c004" },
  { id: "P005", nome: "Silvanira Squiapatti da Silva Lanconi", nivel: "Gerência Executiva", cargo: "Gerente Executivo Administrativo", diretoria: "Administrativa", chairId: "c005" },
  { id: "P006", nome: "Amaya Fernanda Dal Coleto de Albuquerque", nivel: "Gerência Executiva", cargo: "Gerente Executivo Financeiro", diretoria: "Financeira", chairId: "c006" },
  { id: "P008", nome: "Nelson Alves Quagliato", nivel: "Gerência Executiva", cargo: "Gerente Executivo Comercial Regional 2", diretoria: "Negócios", chairId: "c008" },
  { id: "P009", nome: "Rafael Cavallante de Oliveira", nivel: "Gerência Executiva", cargo: "Gerente Executivo Comercial Regional 1", diretoria: "Negócios", chairId: "c009" },
  { id: "P010", nome: "Matheus Ferreira", nivel: "Gerência", cargo: "Gerente de T.i.", diretoria: "Administrativa", chairId: "c010" },
  { id: "P011", nome: "Cristiano Aparecido Cremonese", nivel: "Gerência", cargo: "Gerente de Contabilidade", diretoria: "Financeira", chairId: "c011" },
  { id: "P012", nome: "Luis Guilherme Apolinario", nivel: "Gerência", cargo: "Gerente Financeiro", diretoria: "Financeira", chairId: "c012" },
  { id: "P013", nome: "Luiz Tiago Correa Moretti", nivel: "Gerência", cargo: "Gerente de Operações", diretoria: "Financeira", chairId: "c013" },
  { id: "P014", nome: "Milene Barratella", nivel: "Gerência", cargo: "Gerente de Operações", diretoria: "Financeira", chairId: "c014" },
  { id: "P015", nome: "Paulo Augusto Barreto Junior", nivel: "Gerência", cargo: "Gerente de Operações", diretoria: "Financeira", chairId: "c015" },
  { id: "P016", nome: "Alessandro Sergio Agatelli", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c016" },
  { id: "P017", nome: "Anaisa Moroni Haddad", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c017" },
  { id: "P018", nome: "Andre Ricardo Trentin", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c018" },
  { id: "P019", nome: "Bruna Hiromi Ushiwa Pimenta", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c019" },
  { id: "P020", nome: "Daniel Aparecido Travaioli", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c020" },
  { id: "P021", nome: "Hipolito Amancio Bizarria Junior", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c021" },
  { id: "P022", nome: "Igor Bolzan Basso", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c022" },
  { id: "P023", nome: "Jose Henrique Diorio Junior", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c023" },
  { id: "P024", nome: "Jose Luiz Pereira Guilherme Junior", nivel: "Gerência", cargo: "Gerente de Performance Corporativa", diretoria: "Negócios", chairId: "c024" },
  { id: "P025", nome: "Jose Paulo Picarelli Avancini", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c025" },
  { id: "P026", nome: "Juliano Zacarias", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c026" },
  { id: "P027", nome: "Julio Augusto de Camargo Toledo", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c027" },
  { id: "P028", nome: "Liliane Patricia Rodrigues Barbosa", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c028" },
  { id: "P029", nome: "Luciane Zanetti", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c029" },
  { id: "P030", nome: "Luiz Rafael Grella", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c030" },
  { id: "P031", nome: "Rogerio Toshio de Castro", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c031" },
  { id: "P032", nome: "Shirlei Aparecida Rossi Ambrozin", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c032" },
  { id: "P033", nome: "Sidnei Roberto Betarelli", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c033" },
  { id: "P034", nome: "Uilian Fernando Ribeiro", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c034" },
  { id: "P098", nome: "Alan Marques", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c098" },
  { id: "P099", nome: "Alex Henrique Ambrosio", nivel: "Gerência", cargo: "Gerente de Relacionamento I", diretoria: "Negócios", chairId: "c099" },
  { id: "P100", nome: "Aline Capelari", nivel: "Gerência", cargo: "Gerente de Relacionamento I", diretoria: "Negócios", chairId: "c100" },
  { id: "P101", nome: "Aline Suzana Lucio", nivel: "Gerência", cargo: "Gerente de Relacionamento I", diretoria: "Negócios", chairId: "c101" },
  { id: "P102", nome: "Ana Paula Leite Santos", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c102" },
  { id: "P103", nome: "Ana Paula Moreira", nivel: "Gerência", cargo: "Gerente de Relacionamento Digital", diretoria: "Negócios", chairId: "c103" },
  { id: "P104", nome: "Anderson Kazunori Ikenoue", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c104" },
  { id: "P105", nome: "Arthur do Nascimento", nivel: "Gerência", cargo: "Gerente de Relacionamento I", diretoria: "Negócios", chairId: "c105" },
  { id: "P106", nome: "Camila Daniel", nivel: "Gerência", cargo: "Gerente de Relacionamento I", diretoria: "Negócios", chairId: "c106" },
  { id: "P107", nome: "Carolina Aparecida Almeida da Silva Mendonca", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c107" },
  { id: "P108", nome: "Celia Rodrigues Alves", nivel: "Gerência", cargo: "Gerente de Relacionamento I", diretoria: "Negócios", chairId: "c108" },
  { id: "P109", nome: "Claudio Roberto de Almeida", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c109" },
  { id: "P110", nome: "Daniela Beneton Caciatore", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c110" },
  { id: "P111", nome: "Daniela de Oliveira Miranda", nivel: "Gerência", cargo: "Gerente de Relacionamento I", diretoria: "Negócios", chairId: "c111" },
  { id: "P112", nome: "Dayna Criser Aparecida Felix Camilo Santos", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c112" },
  { id: "P113", nome: "Denize Nunes Alves", nivel: "Gerência", cargo: "Gerente de Relacionamento I", diretoria: "Negócios", chairId: "c113" },
  { id: "P114", nome: "Douglas Peregrino", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c114" },
  { id: "P115", nome: "Emily Daiane Dias Soares", nivel: "Gerência", cargo: "Gerente de Relacionamento I", diretoria: "Negócios", chairId: "c115" },
  { id: "P116", nome: "Eric Donizeti dos Santos", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c116" },
  { id: "P117", nome: "Fabiana Maria Assalin Dias Pacheco", nivel: "Gerência", cargo: "Gerente de Relacionamento I", diretoria: "Negócios", chairId: "c117" },
  { id: "P118", nome: "Fabio Francis Carlos Nahum", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c118" },
  { id: "P119", nome: "Fabio de Souza Correa Rezende da Costa", nivel: "Gerência", cargo: "Gerente de Relacionamento I", diretoria: "Negócios", chairId: "c119" },
  { id: "P120", nome: "Felipe Augusto Camerin Santarem", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c120" },
  { id: "P121", nome: "Fernando Quibao Neto", nivel: "Gerência", cargo: "Gerente de Relacionamento I", diretoria: "Negócios", chairId: "c121" },
  { id: "P122", nome: "Gabrielle Barbosa de Oliveira Ivolella", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c122" },
  { id: "P123", nome: "Guilherme Tascare", nivel: "Gerência", cargo: "Gerente de Relacionamento I", diretoria: "Negócios", chairId: "c123" },
  { id: "P124", nome: "Gustavo Casarini Del Debbio", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c124" },
  { id: "P125", nome: "Julia Almeida Villa Veronezi", nivel: "Gerência", cargo: "Gerente de Relacionamento I", diretoria: "Negócios", chairId: "c125" },
  { id: "P126", nome: "Julia Wurgler Zorzi", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c126" },
  { id: "P127", nome: "Keli Fernanda da Silva Rodrigues Miranda", nivel: "Gerência", cargo: "Gerente de Relacionamento I", diretoria: "Negócios", chairId: "c127" },
  { id: "P128", nome: "Larissa Fernandes", nivel: "Gerência", cargo: "Gerente de Relacionamento I", diretoria: "Negócios", chairId: "c128" },
  { id: "P129", nome: "Leila de Andrade da Cruz Liberato", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c129" },
  { id: "P130", nome: "Lucas Felicio dos Santos", nivel: "Gerência", cargo: "Gerente de Relacionamento I", diretoria: "Negócios", chairId: "c130" },
  { id: "P131", nome: "Luciano Matheus Pinardi", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c131" },
  { id: "P132", nome: "Luis Fernando Zaratin Marcon", nivel: "Gerência", cargo: "Gerente de Relacionamento I", diretoria: "Negócios", chairId: "c132" },
  { id: "P133", nome: "Luiz Fernando de Almeida Patussi Lima", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c133" },
  { id: "P134", nome: "Luiza Helena Pinto", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c134" },
  { id: "P135", nome: "Marcio Pereira", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c135" },
  { id: "P136", nome: "Mariana Forti Franzzini", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c136" },
  { id: "P137", nome: "Matheus Damasceno Ferreira", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c137" },
  { id: "P138", nome: "Miriane Regina de Almeida Gerevini", nivel: "Gerência", cargo: "Gerente de Relacionamento I", diretoria: "Negócios", chairId: "c138" },
  { id: "P139", nome: "Pedro Antonio Antunes Alves de Almeida", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c139" },
  { id: "P140", nome: "Rafael Rodrigues de Barros Lobo", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c140" },
  { id: "P141", nome: "Rebeca Gabriel Leite Pereira", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c141" },
  { id: "P142", nome: "Reginaldo Oshima de Freitas", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c142" },
  { id: "P143", nome: "Rosaly Schiave Petrin", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c143" },
  { id: "P144", nome: "Sarah Peres Paiva Moreira", nivel: "Gerência", cargo: "Gerente de Relacionamento I", diretoria: "Negócios", chairId: "c144" },
  { id: "P145", nome: "Talita Cortes Radeschi Cavinatto", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c145" },
  { id: "P146", nome: "Tatiane Piccin", nivel: "Gerência", cargo: "Gerente de Relacionamento I", diretoria: "Negócios", chairId: "c146" },
  { id: "P147", nome: "Thainara Lorenzon Cervelin", nivel: "Gerência", cargo: "Gerente de Relacionamento II", diretoria: "Negócios", chairId: "c147" },
  { id: "P148", nome: "Vagner Lopes", nivel: "Gerência", cargo: "Gerente de Relacionamento I", diretoria: "Negócios", chairId: "c148" },
  { id: "P035", nome: "Leila Regina da Silva", nivel: "Coordenação", cargo: "Coordenador de Agronegocios", diretoria: "Negócios", chairId: "c035" },
  { id: "P036", nome: "Renan Henrique Oliveira Muller", nivel: "Coordenação", cargo: "Coordenador de Comunicação e Marketing", diretoria: "Negócios", chairId: "c036" },
  { id: "P037", nome: "Gabriella Fernanda Nichols", nivel: "Coordenação", cargo: "Coordenador de Governança Corporativa", diretoria: "Administrativa", chairId: "c037" },
  { id: "P038", nome: "Larisse de Paula", nivel: "Coordenação", cargo: "Coordenador de Recuperação de Crédito", diretoria: "Financeira", chairId: "c038" },
  { id: "P039", nome: "Renato Alves da Silva", nivel: "Coordenação", cargo: "Coordenador de Suprimentos", diretoria: "Administrativa", chairId: "c039" },
  { id: "P040", nome: "Ailson Lima de Andrade", nivel: "Analista", cargo: "Analista de Performance Corporativa Jr", diretoria: "Negócios", chairId: "c040" },
  { id: "P041", nome: "Aline Avanzi Costa", nivel: "Analista", cargo: "Analista de Suprimentos Jr", diretoria: "Administrativa", chairId: "c041" },
  { id: "P042", nome: "Aline Brambilla da Silva", nivel: "Analista", cargo: "Analista de Gestão de Pessoas Sr", diretoria: "Administrativa", chairId: "c042" },
  { id: "P043", nome: "Andressa Mader Bragion", nivel: "Analista", cargo: "Analista Operacional Jr", diretoria: "Administrativa", chairId: "c043" },
  { id: "P044", nome: "Bianca Beltrame Mattar", nivel: "Analista", cargo: "Analista de Crédito Pl", diretoria: "Financeira", chairId: "c044" },
  { id: "P045", nome: "Enzo Sachs", nivel: "Analista", cargo: "Analista Operacional Jr", diretoria: "Administrativa", chairId: "c045" },
  { id: "P046", nome: "Gabriel Henrique Alves", nivel: "Analista", cargo: "Analista de Tecnologia da Informação Sr", diretoria: "Administrativa", chairId: "c046" },
  { id: "P047", nome: "Jean Felipe Camillo", nivel: "Analista", cargo: "Analista de Performance Corporativa Pl", diretoria: "Negócios", chairId: "c047" },
  { id: "P048", nome: "Jefferson Silva de Oliveira", nivel: "Analista", cargo: "Analista Operacional Jr", diretoria: "Administrativa", chairId: "c048" },
  { id: "P049", nome: "Jessica Goncalves dos Santos", nivel: "Analista", cargo: "Analista Financeiro Sr", diretoria: "Financeira", chairId: "c049" },
  { id: "P050", nome: "Juliana Grossi", nivel: "Analista", cargo: "Analista de Gestão de Pessoas Sr", diretoria: "Administrativa", chairId: "c050" },
  { id: "P051", nome: "Kassio Rodrigo Fogaca", nivel: "Analista", cargo: "Analista de Sistemas Pl", diretoria: "Administrativa", chairId: "c051" },
  { id: "P052", nome: "Katiely Fernanda Correa", nivel: "Analista", cargo: "Analista Contábil Sr", diretoria: "Financeira", chairId: "c052" },
  { id: "P053", nome: "Larissa dos Santos Goncalves", nivel: "Analista", cargo: "Analista de Riscos e Controles Jr", diretoria: "Administrativa", chairId: "c053" },
  { id: "P054", nome: "Ligia Delghingaro Pagotto", nivel: "Analista", cargo: "Analista Financeiro Jr", diretoria: "Financeira", chairId: "c054" },
  { id: "P055", nome: "Luis Fernando Souza Andrade", nivel: "Analista", cargo: "Analista Contábil Jr", diretoria: "Financeira", chairId: "c055" },
  { id: "P056", nome: "Manoela Tebom Santana", nivel: "Analista", cargo: "Analista Operacional Jr", diretoria: "Administrativa", chairId: "c056" },
  { id: "P057", nome: "Mario Henrique Batistella", nivel: "Analista", cargo: "Analista de Performance Corporativa Pl", diretoria: "Negócios", chairId: "c057" },
  { id: "P058", nome: "Matheus Henrique Souza de Moraes", nivel: "Analista", cargo: "Analista de Agronegocios Jr", diretoria: "Negócios", chairId: "c058" },
  { id: "P059", nome: "Monica Roberta Armelin Moraes", nivel: "Analista", cargo: "Analista de Gestão de Pessoas Sr", diretoria: "Administrativa", chairId: "c059" },
  { id: "P060", nome: "Rafael Amaral da Silva", nivel: "Analista", cargo: "Analista Financeiro Pl", diretoria: "Financeira", chairId: "c060" },
  { id: "P061", nome: "Rafael Camilo da Silva", nivel: "Analista", cargo: "Analista de Crédito Jr", diretoria: "Financeira", chairId: "c061" },
  { id: "P062", nome: "Renise Cristina Rolim de Moura", nivel: "Analista", cargo: "Analista de Crédito Jr", diretoria: "Financeira", chairId: "c062" },
  { id: "P063", nome: "Roberto de Lucio", nivel: "Analista", cargo: "Analista Financeiro Pl", diretoria: "Financeira", chairId: "c063" },
  { id: "P064", nome: "Rodolfo Santos Pereira Reges", nivel: "Analista", cargo: "Analista de Administração de Pessoal Jr", diretoria: "Administrativa", chairId: "c064" },
  { id: "P065", nome: "Sabrina Rodrigues de Jesus", nivel: "Analista", cargo: "Analista de Produtos e Serviços Pl", diretoria: "Negócios", chairId: "c065" },
  { id: "P066", nome: "Tiago Fernando Mutti", nivel: "Analista", cargo: "Analista de Riscos e Controles Sr", diretoria: "Administrativa", chairId: "c066" },
  { id: "P067", nome: "Valentina Aparecida Rossi Antonelli", nivel: "Analista", cargo: "Analista de Recuperação de Crédito Jr", diretoria: "Financeira", chairId: "c067" },
  { id: "P068", nome: "Vanessa Cristina Zumesteen", nivel: "Analista", cargo: "Analista de Comunicação e Marketing Jr", diretoria: "Negócios", chairId: "c068" },
  { id: "P069", nome: "Yara Cerezer Pereira", nivel: "Analista", cargo: "Analista de Produtos e Serviços Sr", diretoria: "Negócios", chairId: "c069" },
  { id: "P070", nome: "Yasmin Aparecida da Silva Castro", nivel: "Analista", cargo: "Analista de Produtos e Serviços Jr", diretoria: "Negócios", chairId: "c070" },
  { id: "P071", nome: "Alexia Maria Cezar de Souza", nivel: "Coordenação", cargo: "Coordenador Administrativo de P.A.", diretoria: "Negócios", chairId: "c071" },
  { id: "P072", nome: "Amelia Cristina Angelieri Barbosa", nivel: "Coordenação", cargo: "Coordenador Administrativo de P.A.", diretoria: "Negócios", chairId: "c072" },
  { id: "P073", nome: "Aristeu Serafim Junior", nivel: "Coordenação", cargo: "Coordenador Administrativo de P.A.", diretoria: "Negócios", chairId: "c073" },
  { id: "P074", nome: "Bruna de Araujo Santos", nivel: "Coordenação", cargo: "Coordenador Administrativo de P.A.", diretoria: "Negócios", chairId: "c074" },
  { id: "P075", nome: "Bruna Torres", nivel: "Coordenação", cargo: "Coordenador Administrativo de P.A.", diretoria: "Negócios", chairId: "c075" },
  { id: "P076", nome: "Bruno Werner Pasqualini", nivel: "Coordenação", cargo: "Coordenador Administrativo de P.A.", diretoria: "Negócios", chairId: "c076" },
  { id: "P077", nome: "Camila Morais de Mello", nivel: "Coordenação", cargo: "Coordenador Administrativo de P.A.", diretoria: "Negócios", chairId: "c077" },
  { id: "P078", nome: "Danilo Borsato", nivel: "Coordenação", cargo: "Coordenador Administrativo de P.A.", diretoria: "Negócios", chairId: "c078" },
  { id: "P079", nome: "Diego Domingues", nivel: "Coordenação", cargo: "Coordenador Administrativo de P.A.", diretoria: "Negócios", chairId: "c079" },
  { id: "P080", nome: "Elaine Fumiko Sato Rodrigues", nivel: "Coordenação", cargo: "Coordenador Administrativo de P.A.", diretoria: "Negócios", chairId: "c080" },
  { id: "P081", nome: "Gracia do Couto", nivel: "Coordenação", cargo: "Coordenador Administrativo de P.A.", diretoria: "Negócios", chairId: "c081" },
  { id: "P082", nome: "Leticia Fernanda Machado", nivel: "Coordenação", cargo: "Coordenador Administrativo de P.A.", diretoria: "Negócios", chairId: "c082" },
  { id: "P083", nome: "Luana Cristina Camargo Estanislau", nivel: "Coordenação", cargo: "Coordenador Administrativo de P.A.", diretoria: "Negócios", chairId: "c083" },
  { id: "P084", nome: "Marcos Paulo Rapete Canatelli", nivel: "Coordenação", cargo: "Coordenador Administrativo de P.A.", diretoria: "Negócios", chairId: "c084" },
  { id: "P085", nome: "Nivaldo Armelin Junior", nivel: "Coordenação", cargo: "Coordenador Administrativo de P.A.", diretoria: "Negócios", chairId: "c085" },
  { id: "P086", nome: "Rafael Moretti Queiroz", nivel: "Coordenação", cargo: "Coordenador Administrativo de P.A.", diretoria: "Negócios", chairId: "c086" },
  { id: "P087", nome: "Renata Trevisan Leme Araujo", nivel: "Coordenação", cargo: "Coordenador Administrativo de P.A.", diretoria: "Negócios", chairId: "c087" },
  { id: "P088", nome: "Rodrigo Dias de Oliveira", nivel: "Coordenação", cargo: "Coordenador Administrativo de P.A.", diretoria: "Negócios", chairId: "c088" },
  { id: "P089", nome: "Vanessa de Lourdes Ferrarezi", nivel: "Coordenação", cargo: "Coordenador Administrativo de P.A.", diretoria: "Negócios", chairId: "c089" },
  { id: "P090", nome: "Anderson Vasconcelos Gava", nivel: "Especialista", cargo: "Especialista de Produtos e Serviços", diretoria: "Negócios", chairId: "c090" },
  { id: "P091", nome: "Fernanda Aparecida Ravanelli Pagotto", nivel: "Especialista", cargo: "Especialista em Supervisão e Monitoramento", diretoria: "Administrativa", chairId: "c091" },
  { id: "P092", nome: "Gabriel Henrique dos Santos Nogueira", nivel: "Especialista", cargo: "Especialista de Produtos e Serviços", diretoria: "Negócios", chairId: "c092" },
  { id: "P093", nome: "Jose Roberto de Araujo", nivel: "Especialista", cargo: "Especialista em Supervisão e Monitoramento", diretoria: "Administrativa", chairId: "c093" },
  { id: "P094", nome: "Leticia Batista Alexandre", nivel: "Especialista", cargo: "Especialista de Produtos e Serviços", diretoria: "Negócios", chairId: "c094" },
  { id: "P095", nome: "Mayara Miori Degaspare", nivel: "Especialista", cargo: "Especialista Operacional de Agronegócios", diretoria: "Negócios", chairId: "c095" },
  { id: "P096", nome: "Suelen Karen de Camargo Marcolino", nivel: "Especialista", cargo: "Especialista de Produtos e Serviços", diretoria: "Negócios", chairId: "c096" },
  { id: "P097", nome: "Tais Regina Torres", nivel: "Especialista", cargo: "Especialista de Performance Corporativa", diretoria: "Negócios", chairId: "c097" },
];

export const HIERARQUIA: HierarquiaEntry[] = [
  { nivel: "C-Level", elegivel: "Diretoria" },
  { nivel: "Diretoria", elegivel: "Gerência Executiva" },
  { nivel: "Gerência Executiva", elegivel: "Gerência" },
  { nivel: "Gerência", elegivel: "Coordenação" },
  { nivel: "Coordenação", elegivel: "Analista" },
];

export const LEVEL_GROUPS: Record<PageKey, string[]> = {
  directors: ["C-Level", "Diretoria"],
  executive: ["Gerência Executiva"],
  management: ["Gerência"],
  coordenacao: ["Coordenação"],
  analista: ["Analista"],
  especialista: ["Especialista"],
};
