import type { Chair, HierarquiaEntry, Person, PageKey } from "./types";

export const CHAIRS: Chair[] = [
  { id: "c001", nome: "Rafael Kerche de Oliveira", cargo: "CEO", nivel: "C-Level", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 10.2, prefixLocalidade: false },
  { id: "c002", nome: "Joao Angelo de Moraes", cargo: "Diretor Administrativo", nivel: "Diretoria", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 2.6, prefixLocalidade: false },
  { id: "c003", nome: "Domingos Savio Oriente Franciulli", cargo: "Diretor de Negócios", nivel: "Diretoria", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 0.1, prefixLocalidade: false },
  { id: "c004", nome: "Cleber Eduardo Vitorino", cargo: "Gerente Executivo de Riscos e Conformidade", nivel: "Gerência Executiva", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 2.0, prefixLocalidade: false },
  { id: "c005", nome: "Silvanira Squiapatti da Silva Lanconi", cargo: "Gerente Executivo Administrativo", nivel: "Gerência Executiva", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 3.2, prefixLocalidade: false },
  { id: "c006", nome: "Amaya Fernanda Dal Coleto de Albuquerque", cargo: "Gerente Executivo Financeiro", nivel: "Gerência Executiva", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 16.3, prefixLocalidade: false },
  { id: "c007", nome: "", cargo: "Gerente Executivo de Negócios", nivel: "Gerência Executiva", diretoria: "Negócios", cidade: "Capivari", tempoCasa: null, prefixLocalidade: false, vago: true },
  { id: "c008", nome: "Nelson Alves Quagliato", cargo: "Gerente Executivo Comercial Regional 2", nivel: "Gerência Executiva", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 10.4, prefixLocalidade: false },
  { id: "c009", nome: "Rafael Cavallante de Oliveira", cargo: "Gerente Executivo Comercial Regional 1", nivel: "Gerência Executiva", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 13.9, prefixLocalidade: false },
  { id: "c010", nome: "Matheus Ferreira", cargo: "Gerente de T.i.", nivel: "Gerência", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 7.5, prefixLocalidade: false },
  { id: "c011", nome: "Cristiano Aparecido Cremonese", cargo: "Gerente de Contabilidade", nivel: "Gerência", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 9.8, prefixLocalidade: false },
  { id: "c012", nome: "Luis Guilherme Apolinario", cargo: "Gerente Financeiro", nivel: "Gerência", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 10.7, prefixLocalidade: false },
  { id: "c013", nome: "Luiz Tiago Correa Moretti", cargo: "Gerente de Operações", nivel: "Gerência", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 4.1, prefixLocalidade: false },
  { id: "c014", nome: "Milene Barratella", cargo: "Gerente de Operações", nivel: "Gerência", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 10.1, prefixLocalidade: false },
  { id: "c015", nome: "Paulo Augusto Barreto Junior", cargo: "Gerente de Operações", nivel: "Gerência", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 1.0, prefixLocalidade: false },
  { id: "c016", nome: "Alessandro Sergio Agatelli", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Itupeva", tempoCasa: 7.5, prefixLocalidade: true },
  { id: "c017", nome: "Anaisa Moroni Haddad", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Rafard", tempoCasa: 8.3, prefixLocalidade: true },
  { id: "c018", nome: "Andre Ricardo Trentin", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Salto", tempoCasa: 3.2, prefixLocalidade: true },
  { id: "c019", nome: "Bruna Hiromi Ushiwa Pimenta", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Porto Feliz", tempoCasa: 15.9, prefixLocalidade: true },
  { id: "c020", nome: "Daniel Aparecido Travaioli", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Monte Mor", tempoCasa: 6.5, prefixLocalidade: true },
  { id: "c021", nome: "Hipolito Amancio Bizarria Junior", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Cesário Lange", tempoCasa: 13.2, prefixLocalidade: true },
  { id: "c022", nome: "Igor Bolzan Basso", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Jumirim", tempoCasa: 6.3, prefixLocalidade: true },
  { id: "c023", nome: "Jose Henrique Diorio Junior", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Tietê", tempoCasa: 2.7, prefixLocalidade: true },
  { id: "c024", nome: "Jose Luiz Pereira Guilherme Junior", cargo: "Gerente de Performance Corporativa", nivel: "Gerência", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 10.6, prefixLocalidade: false },
  { id: "c025", nome: "Jose Paulo Picarelli Avancini", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Vinhedo", tempoCasa: 3.4, prefixLocalidade: true },
  { id: "c026", nome: "Juliano Zacarias", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Boituva", tempoCasa: 5.7, prefixLocalidade: true },
  { id: "c027", nome: "Julio Augusto de Camargo Toledo", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Pereiras", tempoCasa: 10.4, prefixLocalidade: true },
  { id: "c028", nome: "Liliane Patricia Rodrigues Barbosa", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Cabreúva", tempoCasa: 8.6, prefixLocalidade: true },
  { id: "c029", nome: "Luciane Zanetti", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Cerquilho", tempoCasa: 16.8, prefixLocalidade: true },
  { id: "c030", nome: "Luiz Rafael Grella", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Louveira", tempoCasa: 9.0, prefixLocalidade: true },
  { id: "c031", nome: "Rogerio Toshio de Castro", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Indaiatuba", tempoCasa: 4.5, prefixLocalidade: true },
  { id: "c032", nome: "Shirlei Aparecida Rossi Ambrozin", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 7.4, prefixLocalidade: true },
  { id: "c033", nome: "Sidnei Roberto Betarelli", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Elias Fausto", tempoCasa: 5.6, prefixLocalidade: true },
  { id: "c034", nome: "Uilian Fernando Ribeiro", cargo: "Gerente de P.A.", nivel: "Gerência", diretoria: "Negócios", cidade: "Porangaba", tempoCasa: 2.4, prefixLocalidade: true },
  { id: "c035", nome: "Leila Regina da Silva", cargo: "Coordenador de Agronegocios", nivel: "Coordenação", diretoria: "Negócios", cidade: "Capivari", tempoCasa: null, prefixLocalidade: false },
  { id: "c036", nome: "Renan Henrique Oliveira Muller", cargo: "Coordenador de Comunicação e Marketing", nivel: "Coordenação", diretoria: "Negócios", cidade: "Capivari", tempoCasa: null, prefixLocalidade: false },
  { id: "c037", nome: "Gabriella Fernanda Nichols", cargo: "Coordenador de Governança Corporativa", nivel: "Coordenação", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: null, prefixLocalidade: false },
  { id: "c038", nome: "Larisse de Paula", cargo: "Coordenador de Recuperação de Crédito", nivel: "Coordenação", diretoria: "Financeira", cidade: "Capivari", tempoCasa: null, prefixLocalidade: false },
  { id: "c039", nome: "Renato Alves da Silva", cargo: "Coordenador de Suprimentos", nivel: "Coordenação", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: null, prefixLocalidade: false },
  { id: "c040", nome: "Ailson Lima de Andrade", cargo: "Analista de Performance Corporativa Jr", nivel: "Analista", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 4.9, prefixLocalidade: false },
  { id: "c041", nome: "Aline Avanzi Costa", cargo: "Analista de Suprimentos Jr", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 2.1, prefixLocalidade: false },
  { id: "c042", nome: "Aline Brambilla da Silva", cargo: "Analista de Gestão de Pessoas Sr", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 7.9, prefixLocalidade: false },
  { id: "c043", nome: "Andressa Mader Bragion", cargo: "Analista Operacional Jr", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 7.2, prefixLocalidade: false },
  { id: "c044", nome: "Bianca Beltrame Mattar", cargo: "Analista de Crédito Pl", nivel: "Analista", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 7.0, prefixLocalidade: false },
  { id: "c045", nome: "Enzo Sachs", cargo: "Analista Operacional Jr", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 4.2, prefixLocalidade: false },
  { id: "c046", nome: "Gabriel Henrique Alves", cargo: "Analista de Tecnologia da Informação Sr", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 4.2, prefixLocalidade: false },
  { id: "c047", nome: "Jean Felipe Camillo", cargo: "Analista de Performance Corporativa Pl", nivel: "Analista", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 7.0, prefixLocalidade: false },
  { id: "c048", nome: "Jefferson Silva de Oliveira", cargo: "Analista Operacional Jr", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 10.1, prefixLocalidade: false },
  { id: "c049", nome: "Jessica Goncalves dos Santos", cargo: "Analista Financeiro Sr", nivel: "Analista", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 8.8, prefixLocalidade: false },
  { id: "c050", nome: "Juliana Grossi", cargo: "Analista de Gestão de Pessoas Sr", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 3.7, prefixLocalidade: false },
  { id: "c051", nome: "Kassio Rodrigo Fogaca", cargo: "Analista de Sistemas Pl", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 4.9, prefixLocalidade: false },
  { id: "c052", nome: "Katiely Fernanda Correa", cargo: "Analista Contábil Sr", nivel: "Analista", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 8.2, prefixLocalidade: false },
  { id: "c053", nome: "Larissa dos Santos Goncalves", cargo: "Analista de Riscos e Controles Jr", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 4.1, prefixLocalidade: false },
  { id: "c054", nome: "Ligia Delghingaro Pagotto", cargo: "Analista Financeiro Jr", nivel: "Analista", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 5.3, prefixLocalidade: false },
  { id: "c055", nome: "Luis Fernando Souza Andrade", cargo: "Analista Contábil Jr", nivel: "Analista", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 4.7, prefixLocalidade: false },
  { id: "c056", nome: "Manoela Tebom Santana", cargo: "Analista Operacional Jr", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 5.7, prefixLocalidade: false },
  { id: "c057", nome: "Mario Henrique Batistella", cargo: "Analista de Performance Corporativa Pl", nivel: "Analista", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 9.6, prefixLocalidade: false },
  { id: "c058", nome: "Matheus Henrique Souza de Moraes", cargo: "Analista de Agronegocios Jr", nivel: "Analista", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 3.8, prefixLocalidade: false },
  { id: "c059", nome: "Monica Roberta Armelin Moraes", cargo: "Analista de Gestão de Pessoas Sr", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 8.0, prefixLocalidade: false },
  { id: "c060", nome: "Rafael Amaral da Silva", cargo: "Analista Financeiro Pl", nivel: "Analista", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 3.1, prefixLocalidade: false },
  { id: "c061", nome: "Rafael Camilo da Silva", cargo: "Analista de Crédito Jr", nivel: "Analista", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 3.6, prefixLocalidade: false },
  { id: "c062", nome: "Renise Cristina Rolim de Moura", cargo: "Analista de Crédito Jr", nivel: "Analista", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 7.4, prefixLocalidade: false },
  { id: "c063", nome: "Roberto de Lucio", cargo: "Analista Financeiro Pl", nivel: "Analista", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 11.3, prefixLocalidade: false },
  { id: "c064", nome: "Rodolfo Santos Pereira Reges", cargo: "Analista de Administração de Pessoal Jr", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 3.8, prefixLocalidade: false },
  { id: "c065", nome: "Sabrina Rodrigues de Jesus", cargo: "Analista de Produtos e Serviços Pl", nivel: "Analista", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 5.9, prefixLocalidade: false },
  { id: "c066", nome: "Tiago Fernando Mutti", cargo: "Analista de Riscos e Controles Sr", nivel: "Analista", diretoria: "Administrativa", cidade: "Capivari", tempoCasa: 3.2, prefixLocalidade: false },
  { id: "c067", nome: "Valentina Aparecida Rossi Antonelli", cargo: "Analista de Recuperação de Crédito Jr", nivel: "Analista", diretoria: "Financeira", cidade: "Capivari", tempoCasa: 4.5, prefixLocalidade: false },
  { id: "c068", nome: "Vanessa Cristina Zumesteen", cargo: "Analista de Comunicação e Marketing Jr", nivel: "Analista", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 4.7, prefixLocalidade: false },
  { id: "c069", nome: "Yara Cerezer Pereira", cargo: "Analista de Produtos e Serviços Sr", nivel: "Analista", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 8.0, prefixLocalidade: false },
  { id: "c070", nome: "Yasmin Aparecida da Silva Castro", cargo: "Analista de Produtos e Serviços Jr", nivel: "Analista", diretoria: "Negócios", cidade: "Capivari", tempoCasa: 3.7, prefixLocalidade: false },
];

export const PEOPLE: Person[] = [
  { id: "P001", nome: "Rafael Kerche de Oliveira", nivel: "C-Level", cargo: "CEO", diretoria: "Financeira", chairId: "c001" },
  { id: "P002", nome: "Joao Angelo de Moraes", nivel: "Diretoria", cargo: "Diretor Administrativo", diretoria: "Administrativa", chairId: "c002" },
  { id: "P003", nome: "Domingos Savio Oriente Franciulli", nivel: "Diretoria", cargo: "Diretor de Negócios", diretoria: "Negócios", chairId: "c003" },
  { id: "P004", nome: "Cleber Eduardo Vitorino", nivel: "Gerência Executiva", cargo: "Gerente Executivo de Riscos e Conformidade", diretoria: "Administrativa", chairId: "c004" },
  { id: "P005", nome: "Silvanira Squiapatti da Silva Lanconi", nivel: "Gerência Executiva", cargo: "Gerente Executivo Administrativo", diretoria: "Administrativa", chairId: "c005" },
  { id: "P006", nome: "Amaya Fernanda Dal Coleto de Albuquerque", nivel: "Gerência Executiva", cargo: "Gerente Executivo Financeiro", diretoria: "Financeira", chairId: "c006" },
  { id: "P008", nome: "Nelson Alves Quagliato", nivel: "Gerência Executiva", cargo: "Gerente Executivo Comercial Regional 2", diretoria: "Negócios", chairId: "c008" },
  { id: "P009", nome: "Rafael Cavallante de Oliveira", nivel: "Gerência Executiva", cargo: "Gerente Executivo Comercial Regional 1", diretoria: "Negócios", chairId: "c009" },
  { id: "P010", nome: "Matheus Ferreira", nivel: "Gerência", cargo: "Gerente de T.i.", diretoria: "Administrativa", chairId: "c010" },
  { id: "P011", nome: "Cristiano Aparecido Cremonese", nivel: "Gerência", cargo: "Gerente de Contabilidade", diretoria: "Financeira", chairId: "c011" },
  { id: "P012", nome: "Luis Guilherme Apolinario", nivel: "Gerência", cargo: "Gerente Financeiro", diretoria: "Financeira", chairId: "c012" },
  { id: "P013", nome: "Luiz Tiago Correa Moretti", nivel: "Gerência", cargo: "Gerente de Operações", diretoria: "Financeira", chairId: "c013" },
  { id: "P014", nome: "Milene Barratella", nivel: "Gerência", cargo: "Gerente de Operações", diretoria: "Financeira", chairId: "c014" },
  { id: "P015", nome: "Paulo Augusto Barreto Junior", nivel: "Gerência", cargo: "Gerente de Operações", diretoria: "Financeira", chairId: "c015" },
  { id: "P016", nome: "Alessandro Sergio Agatelli", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c016" },
  { id: "P017", nome: "Anaisa Moroni Haddad", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c017" },
  { id: "P018", nome: "Andre Ricardo Trentin", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c018" },
  { id: "P019", nome: "Bruna Hiromi Ushiwa Pimenta", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c019" },
  { id: "P020", nome: "Daniel Aparecido Travaioli", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c020" },
  { id: "P021", nome: "Hipolito Amancio Bizarria Junior", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c021" },
  { id: "P022", nome: "Igor Bolzan Basso", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c022" },
  { id: "P023", nome: "Jose Henrique Diorio Junior", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c023" },
  { id: "P024", nome: "Jose Luiz Pereira Guilherme Junior", nivel: "Gerência", cargo: "Gerente de Performance Corporativa", diretoria: "Negócios", chairId: "c024" },
  { id: "P025", nome: "Jose Paulo Picarelli Avancini", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c025" },
  { id: "P026", nome: "Juliano Zacarias", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c026" },
  { id: "P027", nome: "Julio Augusto de Camargo Toledo", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c027" },
  { id: "P028", nome: "Liliane Patricia Rodrigues Barbosa", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c028" },
  { id: "P029", nome: "Luciane Zanetti", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c029" },
  { id: "P030", nome: "Luiz Rafael Grella", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c030" },
  { id: "P031", nome: "Rogerio Toshio de Castro", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c031" },
  { id: "P032", nome: "Shirlei Aparecida Rossi Ambrozin", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c032" },
  { id: "P033", nome: "Sidnei Roberto Betarelli", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c033" },
  { id: "P034", nome: "Uilian Fernando Ribeiro", nivel: "Gerência", cargo: "Gerente de P.A.", diretoria: "Negócios", chairId: "c034" },
  { id: "P035", nome: "Leila Regina da Silva", nivel: "Coordenação", cargo: "Coordenador de Agronegocios", diretoria: "Negócios", chairId: "c035" },
  { id: "P036", nome: "Renan Henrique Oliveira Muller", nivel: "Coordenação", cargo: "Coordenador de Comunicação e Marketing", diretoria: "Negócios", chairId: "c036" },
  { id: "P037", nome: "Gabriella Fernanda Nichols", nivel: "Coordenação", cargo: "Coordenador de Governança Corporativa", diretoria: "Administrativa", chairId: "c037" },
  { id: "P038", nome: "Larisse de Paula", nivel: "Coordenação", cargo: "Coordenador de Recuperação de Crédito", diretoria: "Financeira", chairId: "c038" },
  { id: "P039", nome: "Renato Alves da Silva", nivel: "Coordenação", cargo: "Coordenador de Suprimentos", diretoria: "Administrativa", chairId: "c039" },
  { id: "P040", nome: "Ailson Lima de Andrade", nivel: "Analista", cargo: "Analista de Performance Corporativa Jr", diretoria: "Negócios", chairId: "c040" },
  { id: "P041", nome: "Aline Avanzi Costa", nivel: "Analista", cargo: "Analista de Suprimentos Jr", diretoria: "Administrativa", chairId: "c041" },
  { id: "P042", nome: "Aline Brambilla da Silva", nivel: "Analista", cargo: "Analista de Gestão de Pessoas Sr", diretoria: "Administrativa", chairId: "c042" },
  { id: "P043", nome: "Andressa Mader Bragion", nivel: "Analista", cargo: "Analista Operacional Jr", diretoria: "Administrativa", chairId: "c043" },
  { id: "P044", nome: "Bianca Beltrame Mattar", nivel: "Analista", cargo: "Analista de Crédito Pl", diretoria: "Financeira", chairId: "c044" },
  { id: "P045", nome: "Enzo Sachs", nivel: "Analista", cargo: "Analista Operacional Jr", diretoria: "Administrativa", chairId: "c045" },
  { id: "P046", nome: "Gabriel Henrique Alves", nivel: "Analista", cargo: "Analista de Tecnologia da Informação Sr", diretoria: "Administrativa", chairId: "c046" },
  { id: "P047", nome: "Jean Felipe Camillo", nivel: "Analista", cargo: "Analista de Performance Corporativa Pl", diretoria: "Negócios", chairId: "c047" },
  { id: "P048", nome: "Jefferson Silva de Oliveira", nivel: "Analista", cargo: "Analista Operacional Jr", diretoria: "Administrativa", chairId: "c048" },
  { id: "P049", nome: "Jessica Goncalves dos Santos", nivel: "Analista", cargo: "Analista Financeiro Sr", diretoria: "Financeira", chairId: "c049" },
  { id: "P050", nome: "Juliana Grossi", nivel: "Analista", cargo: "Analista de Gestão de Pessoas Sr", diretoria: "Administrativa", chairId: "c050" },
  { id: "P051", nome: "Kassio Rodrigo Fogaca", nivel: "Analista", cargo: "Analista de Sistemas Pl", diretoria: "Administrativa", chairId: "c051" },
  { id: "P052", nome: "Katiely Fernanda Correa", nivel: "Analista", cargo: "Analista Contábil Sr", diretoria: "Financeira", chairId: "c052" },
  { id: "P053", nome: "Larissa dos Santos Goncalves", nivel: "Analista", cargo: "Analista de Riscos e Controles Jr", diretoria: "Administrativa", chairId: "c053" },
  { id: "P054", nome: "Ligia Delghingaro Pagotto", nivel: "Analista", cargo: "Analista Financeiro Jr", diretoria: "Financeira", chairId: "c054" },
  { id: "P055", nome: "Luis Fernando Souza Andrade", nivel: "Analista", cargo: "Analista Contábil Jr", diretoria: "Financeira", chairId: "c055" },
  { id: "P056", nome: "Manoela Tebom Santana", nivel: "Analista", cargo: "Analista Operacional Jr", diretoria: "Administrativa", chairId: "c056" },
  { id: "P057", nome: "Mario Henrique Batistella", nivel: "Analista", cargo: "Analista de Performance Corporativa Pl", diretoria: "Negócios", chairId: "c057" },
  { id: "P058", nome: "Matheus Henrique Souza de Moraes", nivel: "Analista", cargo: "Analista de Agronegocios Jr", diretoria: "Negócios", chairId: "c058" },
  { id: "P059", nome: "Monica Roberta Armelin Moraes", nivel: "Analista", cargo: "Analista de Gestão de Pessoas Sr", diretoria: "Administrativa", chairId: "c059" },
  { id: "P060", nome: "Rafael Amaral da Silva", nivel: "Analista", cargo: "Analista Financeiro Pl", diretoria: "Financeira", chairId: "c060" },
  { id: "P061", nome: "Rafael Camilo da Silva", nivel: "Analista", cargo: "Analista de Crédito Jr", diretoria: "Financeira", chairId: "c061" },
  { id: "P062", nome: "Renise Cristina Rolim de Moura", nivel: "Analista", cargo: "Analista de Crédito Jr", diretoria: "Financeira", chairId: "c062" },
  { id: "P063", nome: "Roberto de Lucio", nivel: "Analista", cargo: "Analista Financeiro Pl", diretoria: "Financeira", chairId: "c063" },
  { id: "P064", nome: "Rodolfo Santos Pereira Reges", nivel: "Analista", cargo: "Analista de Administração de Pessoal Jr", diretoria: "Administrativa", chairId: "c064" },
  { id: "P065", nome: "Sabrina Rodrigues de Jesus", nivel: "Analista", cargo: "Analista de Produtos e Serviços Pl", diretoria: "Negócios", chairId: "c065" },
  { id: "P066", nome: "Tiago Fernando Mutti", nivel: "Analista", cargo: "Analista de Riscos e Controles Sr", diretoria: "Administrativa", chairId: "c066" },
  { id: "P067", nome: "Valentina Aparecida Rossi Antonelli", nivel: "Analista", cargo: "Analista de Recuperação de Crédito Jr", diretoria: "Financeira", chairId: "c067" },
  { id: "P068", nome: "Vanessa Cristina Zumesteen", nivel: "Analista", cargo: "Analista de Comunicação e Marketing Jr", diretoria: "Negócios", chairId: "c068" },
  { id: "P069", nome: "Yara Cerezer Pereira", nivel: "Analista", cargo: "Analista de Produtos e Serviços Sr", diretoria: "Negócios", chairId: "c069" },
  { id: "P070", nome: "Yasmin Aparecida da Silva Castro", nivel: "Analista", cargo: "Analista de Produtos e Serviços Jr", diretoria: "Negócios", chairId: "c070" },
];

export const HIERARQUIA: HierarquiaEntry[] = [
  { nivel: "C-Level", elegivel: "Diretoria" },
  { nivel: "Diretoria", elegivel: "Gerência Executiva" },
  { nivel: "Gerência Executiva", elegivel: "Gerência" },
  { nivel: "Gerência", elegivel: "Coordenação" },
  { nivel: "Coordenação", elegivel: "Analista" },
];

export const LEVEL_GROUPS: Record<PageKey, string[]> = {
  directors: ["C-Level", "Diretoria"],
  executive: ["Gerência Executiva"],
  management: ["Gerência"],
  coordenacao: ["Coordenação"],
  analista: ["Analista"],
};
